# Generated by Django 3.2.13 on 2022-05-14 17:55

import uuid
from typing import List, Tuple

import autoslug.fields  # type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(
                    default=None, editable=True, null=True, populate_from='name', unique=True,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
