# Generated by Django 3.2.13 on 2022-06-14 15:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_add_asset_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("K", "Known"), ("L", "Lost"), ("D", "Disposed")],
                        default="K",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "asset_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assetmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "node_type",
                    models.CharField(
                        choices=[("A", "Asset"), ("L", "Location")], max_length=1
                    ),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assetcode",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="assets.asset",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("asset__isnull", False), ("node_type", "A")),
                    models.Q(("asset__isnull", True), ("node_type", "L")),
                    _connector="OR",
                ),
                name="node_type_asset_null_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("name__isnull", False), ("node_type", "L")),
                    ("node_type", "A"),
                    _connector="OR",
                ),
                name="node_type_force_name_if_asset",
            ),
        ),
    ]
