# Generated by Django 3.2.13 on 2022-06-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_add_node_asset_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='state',
        ),
    ]
