# Generated by Django 3.2.13 on 2022-05-14 19:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_add_asset_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('code_type', models.CharField(choices=[('A', 'Arbitrary String'), ('D', 'Damm 32')], max_length=1)),
            ],
        ),
    ]
