# Generated by Django 3.2.13 on 2022-05-14 20:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_add_asset_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(
                    choices=[('K', 'Known'), ('L', 'Lost'), ('D', 'Disposed')], default='K', max_length=1,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assetmodel')),
            ],
        ),
    ]
