# Generated by Django 3.2.13 on 2022-05-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contents',
                to='assets.location',
            ),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('location__isnull', False), ('state', 'K')),
                    models.Q(('location__isnull', True), ('state', 'L')),
                    models.Q(('location__isnull', True), ('state', 'D')),
                    _connector='OR',
                ),
                name='valid_state',
            ),
        ),
    ]
